name: Make GitHub Release
run-name: Making Release from '${{ github.sha }}'

on:
  push:
    branches:
      - main
    paths:
      - "PKGBUILD"
      - ".github/workflows/release-gh.yml"

  workflow_dispatch:

concurrency:
  group: gh-release
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from PKGBUILD
        id: get_version
        run: |
          VER=$(source PKGBUILD && echo $pkgver)

          echo "VERSION=$VER" >> $GITHUB_ENV

          # 3. Check for Beta
          if [[ "$VER" == 0* ]]; then
            echo "IS_PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_ENV
          fi

      - name: Create & Push Tag
        run: |
          git config user.name "soymadip"

          TAG="v${{ env.VERSION }}"

          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping tag creation."
          else
            echo "Creating new Tag: $TAG"
            git tag "$TAG"
            git push origin "$TAG"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        id: generate_changelog
        with:
          config: cliff.toml
          args: --verbose --latest --strip header
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Create app tarball
        run: |
          tar -czf myctl-${{ env.VERSION }}.tar.gz -C app .

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          body_path: CHANGELOG.md
          prerelease: ${{ env.IS_PRERELEASE }}
          files: myctl-${{ env.VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
