name: Make GitHub Release
run-name: "Making Release: ${{ github.ref_name }}"

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - ".github/workflows/release-gh.yml"

  workflow_dispatch:

concurrency:
  group: gh-release
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Get Repo name, Version & Changelog
        id: get_version
        run: |

          # Get Repo name in lower case
          repo_name=$(echo "${GITHUB_REPOSITORY#*/}" | tr '[:upper:]' '[:lower:]')

          # Get latest Tag & version
          latest_tag=$(git describe --tags --abbrev=0 HEAD)
          latest_ver=${latest_tag#v}

          # Get changelog
          changelog=$(uvx --from commitizen cz changelog "${latest_tag}..${latest_tag}" --dry-run | sed -n '/^###/,$p')

          #---------- Export to github_env ------------

          echo "VERSION=$latest_ver" >> "$GITHUB_ENV"
          echo "REPO_NAME=$repo_name" >> "$GITHUB_ENV"
          {
            echo "CHANGELOG<<EOF"
            if [[ -n "$changelog" ]]; then
              echo "## Whats New?"
              echo "$changelog"
            else
              echo "No changes to note."
            fi
            echo "EOF"
          } >> "$GITHUB_ENV"

          if [[ "$latest_ver" == 0* ]]; then
            echo "IS_PRERELEASE=true" >> "$GITHUB_ENV"
          else
            echo "IS_PRERELEASE=false" >> "$GITHUB_ENV"
          fi

      - name: Create app tarball
        run: tar -czf ${{ env.REPO_NAME }}-${{ env.VERSION }}.tar.gz -C app .

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          body: ${{ env.CHANGELOG }}
          prerelease: ${{ env.IS_PRERELEASE == 'true' }}
          files: ${{ env.REPO_NAME }}-${{ env.VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
